package risk;

public enum HumanTurnPhases {
    END_SUB_PHASE, PLACE_ARMIES, ATTACK, SELECT_DEFENDING_TERRITORY, SELECT_ATTACKING_TERRITORY, BATTLE, WON_TERRITORY, FORTIFY_SELECTION, FORTIFY, END_TURN, EDIT
}
